"""Validation issue codes (DF-T-04-004)."""

from __future__ import annotations

# Shape (from ScenarioModel / legacy schema)
SHAPE_VALIDATION_FAILED = "SHAPE_VALIDATION_FAILED"

# Graph
GRAPH_UNREACHABLE_NODE = "GRAPH_UNREACHABLE_NODE"
GRAPH_DEAD_END_NODE = "GRAPH_DEAD_END_NODE"

# Variables
UNDECLARED_VARIABLE = "UNDECLARED_VARIABLE"

# Scenario references
SCENARIO_REF_NOT_FOUND = "SCENARIO_REF_NOT_FOUND"
SCENARIO_VERSION_NOT_FOUND = "SCENARIO_VERSION_NOT_FOUND"
SCENARIO_REF_ARCHIVED = "SCENARIO_REF_ARCHIVED"
SCENARIO_DEPTH_EXCEEDED = "SCENARIO_DEPTH_EXCEEDED"
CIRCULAR_SCENARIO_REFERENCE = "CIRCULAR_SCENARIO_REFERENCE"

# Error policy / retry
INVALID_ON_ERROR_TARGET = "INVALID_ON_ERROR_TARGET"
INVALID_RETRY_CONFIG = "INVALID_RETRY_CONFIG"
RETRY_MAX_ATTEMPTS_OUT_OF_RANGE = "RETRY_MAX_ATTEMPTS_OUT_OF_RANGE"
RETRY_BACKOFF_INVALID = "RETRY_BACKOFF_INVALID"

# Lint (warnings)
NO_VERIFICATION_STEP = "NO_VERIFICATION_STEP"
IMPLICIT_ACCOUNT_FALLBACK = "IMPLICIT_ACCOUNT_FALLBACK"
