# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: relay.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'relay.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brelay.proto\x12\ndevicefarm\"|\n\nVideoFrame\x12\x0e\n\x06serial\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x11\n\tis_config\x18\x03 \x01(\x08\x12\x0e\n\x06is_key\x18\x04 \x01(\x08\x12\x0e\n\x06pts_us\x18\x05 \x01(\x03\x12\r\n\x05width\x18\x06 \x01(\r\x12\x0e\n\x06height\x18\x07 \x01(\r\";\n\nControlMsg\x12\x0e\n\x06serial\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0f\n\x07is_json\x18\x03 \x01(\x08\"N\n\x08\x41gentMsg\x12\'\n\x05video\x18\x01 \x01(\x0b\x32\x16.devicefarm.VideoFrameH\x00\x12\x0e\n\x04meta\x18\x02 \x01(\x0cH\x00\x42\t\n\x07payload2J\n\x0cRelayService\x12:\n\x06Stream\x12\x14.devicefarm.AgentMsg\x1a\x16.devicefarm.ControlMsg(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'relay_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOFRAME']._serialized_start=27
  _globals['_VIDEOFRAME']._serialized_end=151
  _globals['_CONTROLMSG']._serialized_start=153
  _globals['_CONTROLMSG']._serialized_end=212
  _globals['_AGENTMSG']._serialized_start=214
  _globals['_AGENTMSG']._serialized_end=292
  _globals['_RELAYSERVICE']._serialized_start=294
  _globals['_RELAYSERVICE']._serialized_end=368
# @@protoc_insertion_point(module_scope)
