name: PROD CI

on:
  workflow_dispatch:

env:
  APP_NAME: ndatrace-portal-fe
  APP_TAG: ${{ github.sha }}-${{ github.run_number }}
  APP_IMAGE: registry.pila.vn/prod/ndatrace-portal-fe
  REGISTRY_SA: robot$prod
  GITOPS_NAMESPACE: prod
  GITOPS_PRODUCT: layer-3/ndatrace
  GITOPS_FILE: portal-web.yaml

jobs:
  build-push-artifact:
    # environment: staging
    runs-on: medium
    steps:
      - name: Checkout
        uses: 'actions/checkout@v4'

      - name: Authenticate PILA FPT Registry
        run: |-
          docker login -u '${{ env.REGISTRY_SA }}' -p '${{ secrets.ORG_PILA_PROD_PASS }}' registry.pila.vn

      - name: Create file .env
        run: |
          cat << EOF > .env
          ${{ vars.ENV_PROD }}
          EOF

      - name: Build image
        run: |
          export BUILDKIT_PROGRESS=plain
          export DOCKER_BUILDKIT=1
          export BUILDKIT_PARALLELISM=1
          docker build --tag ${{ env.APP_IMAGE }}:${{ env.APP_TAG }} .
        working-directory: .

      - name: Push image & clean up
        run: |
          docker push ${{ env.APP_IMAGE }}:${{ env.APP_TAG }}; 
          docker image rm ${{ env.APP_IMAGE }}:${{ env.APP_TAG }};
