#!/usr/bin/env python3
"""
pack_bundle.py — Pack bundle/ into a single archive for device deployment.

Inspired by LAMDA: instead of pushing many files separately, pack everything
into one tar.gz with a launch.sh — push one file, extract, run launch.sh.

Flow:
    # Step 1: download binaries into device_farm/bundle/ (if not present)
    python ../device_farm/download_bundle.py

    # Step 2: pack into archive
    python pack_bundle.py

    # Step 3: push to device (single file)
    adb push ../device_farm/bundle/device_bundle.tar.gz /data/local/tmp/

    # Step 4: extract + launch on device (one command)
    adb shell "cd /data/local/tmp && tar -xzf device_bundle.tar.gz && sh launch.sh"

Usage:
    python pack_bundle.py          # pack bundle
    python pack_bundle.py --list   # show archive contents
    python pack_bundle.py --force  # rebuild even if archive already exists
"""
from __future__ import annotations

import argparse
import io
import tarfile
from pathlib import Path


_ROOT      = Path(__file__).resolve().parent   # agent-boot/
_FARM_ROOT = _ROOT.parent / "device_farm"      # device_farm/

# Binaries downloaded by device_farm/download_bundle.py
BUNDLE_DIR = _FARM_ROOT / "bundle"

# Output archive placed alongside other bundle files
OUTPUT_DIR = BUNDLE_DIR

# scrcpy-server JAR — prefer relay/ in agent-boot, fall back to device_farm/runtime/
_SCRCPY_CANDIDATES = [
    _ROOT / "relay" / "scrcpy-server",
    _FARM_ROOT / "runtime" / "scrcpy-server",
]

# launch.sh is embedded directly into the archive — no file needed on disk
_LAUNCH_SH = r"""#!/bin/sh
# launch.sh — Start Device Farm agent tools on device.
# Auto-generated by agent-boot/pack_bundle.py — do not edit manually.
#
# Run after extract:
#   tar -xzf device_bundle.tar.gz && sh launch.sh

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Install APKs if not already installed
_install_apk() {
    pkg="$1"; apk="$2"
    if ! pm path "$pkg" > /dev/null 2>&1; then
        echo "[launch] Installing $apk ..."
        pm install -r -t "$SCRIPT_DIR/apks/$apk" \
            && echo "[launch] OK: $apk" \
            || echo "[launch] WARN: install failed for $apk"
    else
        echo "[launch] Already installed: $pkg"
    fi
}

_install_apk "com.github.uiautomator"      "app-uiautomator.apk"
_install_apk "com.github.uiautomator.test" "app-uiautomator-test.apk"

# Start atx-agent HTTP bridge on port 7912 (if binary is present in bundle)
ATX_BIN="$SCRIPT_DIR/atx-agent/atx-agent-arm64"
if [ -x "$ATX_BIN" ]; then
    echo "[launch] Starting atx-agent on :7912 ..."
    "$ATX_BIN" server --stop >/dev/null 2>&1 || true
    "$ATX_BIN" server --addr :7912 >/tmp/atx-agent.log 2>&1 &
    echo "[launch] atx-agent started (pid=$!) log:/tmp/atx-agent.log"
else
    echo "[launch] WARN: atx-agent binary not found at $ATX_BIN"
fi

# Start uiautomator2 server
echo "[launch] Starting uiautomator2-server ..."
dumpsys deviceidle whitelist +com.github.uiautomator      2>/dev/null || true
dumpsys deviceidle whitelist +com.github.uiautomator.test 2>/dev/null || true
am force-stop com.github.uiautomator 2>/dev/null || true
am instrument -w -e timeout 0 \
    com.github.uiautomator.test/androidx.test.runner.AndroidJUnitRunner \
    > /tmp/u2-server.log 2>&1 &
echo "[launch] uiautomator2-server started (pid=$!), log: /tmp/u2-server.log"
echo "[launch] Done."
"""


def _has_apks() -> bool:
    return (
        (BUNDLE_DIR / "apks" / "app-uiautomator.apk").is_file()
        and (BUNDLE_DIR / "apks" / "app-uiautomator-test.apk").is_file()
    )


def pack_bundle(force: bool = False) -> Path | None:
    out = OUTPUT_DIR / "device_bundle.tar.gz"

    if out.exists() and not force:
        print(f"  {out.name}: already exists (use --force to rebuild)")
        return out

    if not _has_apks():
        print("  WARN: APKs missing from bundle/apks/ — run: python ../device_farm/download_bundle.py")
        return None

    print(f"  Packing -> {out.name} ...")
    with tarfile.open(out, "w:gz") as tar:
        # Embed launch.sh inline
        launch_bytes = _LAUNCH_SH.encode("utf-8")
        info = tarfile.TarInfo(name="launch.sh")
        info.size = len(launch_bytes)
        info.mode = 0o755
        tar.addfile(info, io.BytesIO(launch_bytes))

        # APKs
        for apk_name in ["app-uiautomator.apk", "app-uiautomator-test.apk", "STFService.apk"]:
            src = BUNDLE_DIR / "apks" / apk_name
            if src.exists():
                tar.add(src, arcname=f"apks/{apk_name}")

        # atx-agent binaries (all ABIs present in bundle/)
        for atx_src in sorted((BUNDLE_DIR / "atx-agent").glob("atx-agent-*")):
            tar.add(atx_src, arcname=f"atx-agent/{atx_src.name}")

        # scrcpy-server JAR
        scrcpy_src = next((p for p in _SCRCPY_CANDIDATES if p.is_file()), None)
        if scrcpy_src:
            tar.add(scrcpy_src, arcname="scrcpy-server")
        else:
            print("  WARN: scrcpy-server not found — run: python ../device_farm/download_bundle.py --scrcpy-only")

    size_kb = out.stat().st_size // 1024
    print(f"  OK: {out.name} ({size_kb:,} KB)")
    return out


def list_archive() -> None:
    arc = OUTPUT_DIR / "device_bundle.tar.gz"
    if not arc.exists():
        print("No archive found. Run: python pack_bundle.py")
        return
    size_kb = arc.stat().st_size // 1024
    with tarfile.open(arc, "r:gz") as tar:
        members = tar.getnames()
    print(f"{arc.name}  ({size_kb:,} KB)  —  {len(members)} files:")
    for m in members:
        print(f"  {m}")


def print_deploy_guide(arc: Path) -> None:
    print("\n" + "=" * 60)
    print("Deploy to device")
    print("=" * 60)
    print(f"\n  adb push ../device_farm/bundle/{arc.name} /data/local/tmp/")
    print(f"  adb shell 'cd /data/local/tmp && tar -xzf {arc.name} && sh launch.sh'")
    print()


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Pack device_farm/bundle/ into device_bundle.tar.gz"
    )
    ap.add_argument("--force", action="store_true", help="Rebuild even if archive exists")
    ap.add_argument("--list",  action="store_true", help="Show archive contents")
    args = ap.parse_args()

    if args.list:
        list_archive()
        return

    print("=" * 60)
    print("Device Farm — Pack Device Bundle")
    print(f"Source : {BUNDLE_DIR}")
    print(f"Output : {OUTPUT_DIR}")
    print("=" * 60)

    result = pack_bundle(force=args.force)
    if result:
        print_deploy_guide(result)


if __name__ == "__main__":
    main()
