# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import relay_pb2 as relay__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in relay_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RelayServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Stream = channel.stream_stream(
                '/devicefarm.RelayService/Stream',
                request_serializer=relay__pb2.AgentMsg.SerializeToString,
                response_deserializer=relay__pb2.ControlMsg.FromString,
                _registered_method=True)


class RelayServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Stream(self, request_iterator, context):
        """Single bidirectional stream per agent-boot instance.
        Agent sends AgentMsgs (video + JSON); farm sends ControlMsgs (control + JSON commands).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RelayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Stream': grpc.stream_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=relay__pb2.AgentMsg.FromString,
                    response_serializer=relay__pb2.ControlMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'devicefarm.RelayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('devicefarm.RelayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RelayService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/devicefarm.RelayService/Stream',
            relay__pb2.AgentMsg.SerializeToString,
            relay__pb2.ControlMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AgentControlServiceStub(object):
    """── Control plane (separate stream, low-volume) ───────────────────────────────
    Runs on the same gRPC port as RelayService but as an independent HTTP/2 stream.
    This keeps identity + command traffic off the high-throughput video stream.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ControlStream = channel.stream_stream(
                '/devicefarm.AgentControlService/ControlStream',
                request_serializer=relay__pb2.AgentControlMsg.SerializeToString,
                response_deserializer=relay__pb2.ServerControlMsg.FromString,
                _registered_method=True)


class AgentControlServiceServicer(object):
    """── Control plane (separate stream, low-volume) ───────────────────────────────
    Runs on the same gRPC port as RelayService but as an independent HTTP/2 stream.
    This keeps identity + command traffic off the high-throughput video stream.

    """

    def ControlStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ControlStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ControlStream,
                    request_deserializer=relay__pb2.AgentControlMsg.FromString,
                    response_serializer=relay__pb2.ServerControlMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'devicefarm.AgentControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('devicefarm.AgentControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentControlService(object):
    """── Control plane (separate stream, low-volume) ───────────────────────────────
    Runs on the same gRPC port as RelayService but as an independent HTTP/2 stream.
    This keeps identity + command traffic off the high-throughput video stream.

    """

    @staticmethod
    def ControlStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/devicefarm.AgentControlService/ControlStream',
            relay__pb2.AgentControlMsg.SerializeToString,
            relay__pb2.ServerControlMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MediaAdapterControlServiceStub(object):
    """── Media adapter control plane ──────────────────────────────────────────────
    Local media-adapter opens this outbound stream to the cloud backend. Only
    lifecycle/signaling/status messages travel here. H264 media must be published
    directly from media-adapter to go2rtc, never through this gRPC service.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ControlStream = channel.stream_stream(
                '/devicefarm.MediaAdapterControlService/ControlStream',
                request_serializer=relay__pb2.MediaAdapterMsg.SerializeToString,
                response_deserializer=relay__pb2.MediaAdapterCommand.FromString,
                _registered_method=True)


class MediaAdapterControlServiceServicer(object):
    """── Media adapter control plane ──────────────────────────────────────────────
    Local media-adapter opens this outbound stream to the cloud backend. Only
    lifecycle/signaling/status messages travel here. H264 media must be published
    directly from media-adapter to go2rtc, never through this gRPC service.

    """

    def ControlStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediaAdapterControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ControlStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ControlStream,
                    request_deserializer=relay__pb2.MediaAdapterMsg.FromString,
                    response_serializer=relay__pb2.MediaAdapterCommand.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'devicefarm.MediaAdapterControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('devicefarm.MediaAdapterControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MediaAdapterControlService(object):
    """── Media adapter control plane ──────────────────────────────────────────────
    Local media-adapter opens this outbound stream to the cloud backend. Only
    lifecycle/signaling/status messages travel here. H264 media must be published
    directly from media-adapter to go2rtc, never through this gRPC service.

    """

    @staticmethod
    def ControlStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/devicefarm.MediaAdapterControlService/ControlStream',
            relay__pb2.MediaAdapterMsg.SerializeToString,
            relay__pb2.MediaAdapterCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
