apiVersion: v1
kind: Service
metadata:
  name: {{ include "device-farm-runtime.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "device-farm-runtime.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
