class MsgType:

    DO_IDENTIFY = 1
    DO_KEYEVENT = 2
    DO_TYPE = 3
    DO_WAKE = 4
    GET_BROWSERS = 5
    GET_CLIPBOARD = 6
    GET_PROPERTIES = 7
    GET_VERSION = 8
    SET_CLIPBOARD = 9
    SET_KEYGUARD_STATE = 10
    SET_WAKE_LOCK = 11
    SET_ROTATION = 12
    EVENT_AIRPLANE_MODE = 13
    EVENT_BATTERY = 14
    EVENT_CONNECTIVITY = 15
    EVENT_PHONE_STATE = 16
    EVENT_ROTATION = 17
    EVENT_BROWSER_PACKAGE = 18
    GET_DISPLAY = 19
    DO_REMOVE_ACCOUNT = 20
    SET_RINGER_MODE = 21
    SET_WIFI_ENABLED = 22
    GET_WIFI_STATUS = 23
    DO_ADD_ACCOUNT_MENU = 24
    GET_SD_STATUS = 25
    GET_ACCOUNTS = 26
    GET_RINGER_MODE = 27
    SET_MASTER_MUTE = 28
    GET_BLUETOOTH_STATUS = 29
    SET_BLUETOOTH_ENABLED = 30
    GET_ROOT_STATUS = 31
    DO_CLEAN_BLUETOOTH_BONDED = 32

