'use client';

import {
  MousePointerClick,
  MoveRight,
  ArrowDownToLine,
  ArrowLeft,
  Keyboard,
  Terminal,
  Smartphone,
  SquareX,
  Eraser,
  AppWindow,
  Upload,
  Download,
  Globe,
  PackagePlus,
  Timer,
  Search,
  CheckCircle,
  XCircle,
  Variable,
  Repeat,
  Repeat1,
  GitBranch,
  Dice5,
  Package,
  Hand,
  CircleDot,
  ZoomIn,
  GripVertical,
  Camera,
  Clipboard,
  Users,
  UserPlus,
  MessageCircle,
  type LucideProps
} from 'lucide-react';
import { cn } from '@/lib/utils';

const ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  tap: MousePointerClick,
  tap_ratio: CircleDot,
  tap_position: CircleDot,
  tap_selector: MousePointerClick,
  long_tap_selector: Hand,
  swipe_ratio: MoveRight,
  input_text: Keyboard,
  input_selector: Keyboard,
  key: Keyboard,
  key_back: ArrowLeft,
  adb_shell: Terminal,
  launch_app: Smartphone,
  stop_app: SquareX,
  clear_app: Eraser,
  wait_app: AppWindow,
  push_file: Upload,
  pull_file: Download,
  open_url: Globe,
  install_apk: PackagePlus,
  scroll_down: ArrowDownToLine,
  scroll_to: ArrowDownToLine,
  wait: Timer,
  wait_element: Search,
  wait_stable: Timer,
  verify_screen: CheckCircle,
  assert_element: CheckCircle,
  dismiss_popup: XCircle,
  login_if_needed: CheckCircle,
  platform_session_gate: CheckCircle,
  fill_form: Keyboard,
  assert_app_state: CheckCircle,
  set_variable: Variable,
  set_var: Variable,
  repeat: Repeat,
  repeat_until: Repeat1,
  if_element: GitBranch,
  if_variable: GitBranch,
  random_pick: Dice5,
  run_scenario: Package,
  double_tap: MousePointerClick,
  pinch: ZoomIn,
  drag: GripVertical,
  take_screenshot: Camera,
  set_clipboard: Clipboard,
  use_source_pool: Users,
  lease_source_target: Search,
  lease_connection_candidate: UserPlus,
  extract_text_hierarchy: Search,
  extract_text_ocr: Search,
  extract_text_ai: Search,
  extract_screen_data: Search,
  if: GitBranch,
  break_if: GitBranch,
  social_open_comments: GitBranch,
  social_find_comment_button: Search,
  social_tap_comment_target: MousePointerClick,
  social_apply_comment_filter: CheckCircle,
  social_scan_posts_interact: MessageCircle,
  social_open_author_from_post_match: UserPlus,
  social_open_commenter_from_post_match: UserPlus,
  social_content_like_comment_flow: MessageCircle,
  content_interaction: MousePointerClick,
  connection_request: UserPlus,
  community_membership: Users,
  extract_comments: Search,
  extract_posts: Search
};

const COLOR_MAP: Record<string, string> = {
  tap: 'text-blue-500',
  tap_ratio: 'text-blue-500',
  tap_position: 'text-blue-500',
  tap_selector: 'text-blue-500',
  long_tap_selector: 'text-blue-500',
  swipe_ratio: 'text-blue-500',
  input_text: 'text-cyan-500',
  input_selector: 'text-cyan-500',
  key: 'text-cyan-500',
  key_back: 'text-cyan-500',
  adb_shell: 'text-slate-500',
  launch_app: 'text-indigo-500',
  stop_app: 'text-indigo-500',
  clear_app: 'text-indigo-500',
  wait_app: 'text-indigo-500',
  push_file: 'text-indigo-500',
  pull_file: 'text-indigo-500',
  open_url: 'text-indigo-500',
  install_apk: 'text-indigo-500',
  scroll_down: 'text-indigo-400',
  scroll_to: 'text-indigo-400',
  wait: 'text-green-500',
  wait_element: 'text-green-500',
  wait_stable: 'text-green-500',
  verify_screen: 'text-green-500',
  assert_element: 'text-green-600',
  dismiss_popup: 'text-red-400',
  login_if_needed: 'text-emerald-500',
  platform_session_gate: 'text-emerald-600',
  fill_form: 'text-cyan-600',
  assert_app_state: 'text-green-600',
  double_tap: 'text-blue-400',
  pinch: 'text-sky-500',
  drag: 'text-blue-600',
  take_screenshot: 'text-violet-500',
  set_clipboard: 'text-teal-500',
  use_source_pool: 'text-teal-600',
  lease_source_target: 'text-cyan-600',
  lease_connection_candidate: 'text-emerald-600',
  set_variable: 'text-purple-500',
  set_var: 'text-purple-500',
  repeat: 'text-orange-500',
  repeat_until: 'text-orange-500',
  if_element: 'text-amber-500',
  if_variable: 'text-amber-500',
  random_pick: 'text-rose-500',
  run_scenario: 'text-pink-500',
  extract_text_hierarchy: 'text-fuchsia-500',
  extract_text_ocr: 'text-fuchsia-500',
  extract_text_ai: 'text-fuchsia-500',
  extract_screen_data: 'text-fuchsia-500',
  if: 'text-amber-500',
  break_if: 'text-amber-500',
  social_open_comments: 'text-blue-600',
  social_find_comment_button: 'text-sky-600',
  social_tap_comment_target: 'text-blue-600',
  social_apply_comment_filter: 'text-emerald-600',
  social_scan_posts_interact: 'text-blue-600',
  social_open_author_from_post_match: 'text-emerald-700',
  social_open_commenter_from_post_match: 'text-emerald-700',
  extract_comments: 'text-fuchsia-500',
  extract_posts: 'text-fuchsia-500'
};

interface Props {
  type: string;
  size?: number;
  className?: string;
}

export function StepIcon({ type, size = 12, className }: Props) {
  const Icon = ICON_MAP[type] ?? MousePointerClick;
  const color = COLOR_MAP[type] ?? 'text-muted-foreground';
  return <Icon size={size} className={cn(color, className)} />;
}
