export const DEVICE_TARGET_FORM_KEY = '_target_form';

const CONTROLLED_TARGET_KEYS = new Set([
  DEVICE_TARGET_FORM_KEY,
  'TARGET_ENTITY_ID',
  'TARGET_ENTITY_IDS',
  'TARGET_ENTITY_TYPE',
  'TARGET_ENTITY_TYPES',
  'TARGET_EXTERNAL_ID',
  'TARGET_NAME',
  'TARGET_NAMES',
  'TARGET_PLATFORM',
  'TARGET_URL',
  'TARGET_SEARCH_QUERY',
  'TARGET_SELECTOR_BY',
  'TARGET_SELECTOR_VALUE',
  'TARGET_FALLBACK_SELECTOR_BY',
  'TARGET_FALLBACK_SELECTOR_VALUE',
  'TARGET_LOCATOR',
  'GROUP_NAME',
  'TARGET_GROUP_NAME',
  'GROUP_COUNT',
  'GROUP_SEARCHES',
  'GROUP_ROW_TEXTS',
  'GROUP_TARGET_IDS',
  'GROUP_TARGETS',
  'PAGE_TARGET_IDS',
  'PAGE_TARGETS',
  'PROFILE_TARGET_IDS',
  'PROFILE_TARGETS'
]);

export function isDeviceTargetFormControlledKey(key: string): boolean {
  return CONTROLLED_TARGET_KEYS.has(key);
}
