import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconBrandGoogle,
  IconChartBar,
  IconBuilding,
  IconList,
  IconCertificate,
  IconKey,
  IconRoute,
  IconPackage,
  IconHistory,
  IconLocationPlus,
  IconBell,
  IconBellFilled,
  IconMessageCircle,
  IconLink,
  IconDeviceMobile,
  IconPlayerPlay
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  google: IconBrandGoogle,
  stats: IconChartBar,
  building: IconBuilding,
  batch: IconList,
  vc: IconCertificate,
  key: IconKey,
  flow: IconRoute,
  inventory: IconPackage,
  history: IconHistory,
  gln: IconLocationPlus,
  bell: IconBell,
  bellFilled: IconBellFilled,
  messageCircle: IconMessageCircle,
  link: IconLink,
  revoke: IconTrash,
  smartphone: IconDeviceMobile,
  play: IconPlayerPlay
};
