// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: relay.proto

package relaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RelayService_Stream_FullMethodName = "/devicefarm.RelayService/Stream"
)

// RelayServiceClient is the client API for RelayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelayServiceClient interface {
	// Single bidirectional stream per agent-boot instance.
	// Agent sends AgentMsgs (video + JSON); farm sends ControlMsgs (control + JSON commands).
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMsg, ControlMsg], error)
}

type relayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayServiceClient(cc grpc.ClientConnInterface) RelayServiceClient {
	return &relayServiceClient{cc}
}

func (c *relayServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMsg, ControlMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RelayService_ServiceDesc.Streams[0], RelayService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMsg, ControlMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RelayService_StreamClient = grpc.BidiStreamingClient[AgentMsg, ControlMsg]

// RelayServiceServer is the server API for RelayService service.
// All implementations must embed UnimplementedRelayServiceServer
// for forward compatibility.
type RelayServiceServer interface {
	// Single bidirectional stream per agent-boot instance.
	// Agent sends AgentMsgs (video + JSON); farm sends ControlMsgs (control + JSON commands).
	Stream(grpc.BidiStreamingServer[AgentMsg, ControlMsg]) error
	mustEmbedUnimplementedRelayServiceServer()
}

// UnimplementedRelayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayServiceServer struct{}

func (UnimplementedRelayServiceServer) Stream(grpc.BidiStreamingServer[AgentMsg, ControlMsg]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedRelayServiceServer) mustEmbedUnimplementedRelayServiceServer() {}
func (UnimplementedRelayServiceServer) testEmbeddedByValue()                      {}

// UnsafeRelayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayServiceServer will
// result in compilation errors.
type UnsafeRelayServiceServer interface {
	mustEmbedUnimplementedRelayServiceServer()
}

func RegisterRelayServiceServer(s grpc.ServiceRegistrar, srv RelayServiceServer) {
	// If the following call panics, it indicates UnimplementedRelayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelayService_ServiceDesc, srv)
}

func _RelayService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RelayServiceServer).Stream(&grpc.GenericServerStream[AgentMsg, ControlMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RelayService_StreamServer = grpc.BidiStreamingServer[AgentMsg, ControlMsg]

// RelayService_ServiceDesc is the grpc.ServiceDesc for RelayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devicefarm.RelayService",
	HandlerType: (*RelayServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _RelayService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "relay.proto",
}

const (
	AgentControlService_ControlStream_FullMethodName = "/devicefarm.AgentControlService/ControlStream"
)

// AgentControlServiceClient is the client API for AgentControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentControlServiceClient interface {
	ControlStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentControlMsg, ServerControlMsg], error)
}

type agentControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentControlServiceClient(cc grpc.ClientConnInterface) AgentControlServiceClient {
	return &agentControlServiceClient{cc}
}

func (c *agentControlServiceClient) ControlStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentControlMsg, ServerControlMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControlService_ServiceDesc.Streams[0], AgentControlService_ControlStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentControlMsg, ServerControlMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControlService_ControlStreamClient = grpc.BidiStreamingClient[AgentControlMsg, ServerControlMsg]

// AgentControlServiceServer is the server API for AgentControlService service.
// All implementations must embed UnimplementedAgentControlServiceServer
// for forward compatibility.
type AgentControlServiceServer interface {
	ControlStream(grpc.BidiStreamingServer[AgentControlMsg, ServerControlMsg]) error
	mustEmbedUnimplementedAgentControlServiceServer()
}

// UnimplementedAgentControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentControlServiceServer struct{}

func (UnimplementedAgentControlServiceServer) ControlStream(grpc.BidiStreamingServer[AgentControlMsg, ServerControlMsg]) error {
	return status.Error(codes.Unimplemented, "method ControlStream not implemented")
}
func (UnimplementedAgentControlServiceServer) mustEmbedUnimplementedAgentControlServiceServer() {}
func (UnimplementedAgentControlServiceServer) testEmbeddedByValue()                             {}

// UnsafeAgentControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentControlServiceServer will
// result in compilation errors.
type UnsafeAgentControlServiceServer interface {
	mustEmbedUnimplementedAgentControlServiceServer()
}

func RegisterAgentControlServiceServer(s grpc.ServiceRegistrar, srv AgentControlServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentControlService_ServiceDesc, srv)
}

func _AgentControlService_ControlStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentControlServiceServer).ControlStream(&grpc.GenericServerStream[AgentControlMsg, ServerControlMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControlService_ControlStreamServer = grpc.BidiStreamingServer[AgentControlMsg, ServerControlMsg]

// AgentControlService_ServiceDesc is the grpc.ServiceDesc for AgentControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devicefarm.AgentControlService",
	HandlerType: (*AgentControlServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ControlStream",
			Handler:       _AgentControlService_ControlStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "relay.proto",
}

const (
	MediaAdapterControlService_ControlStream_FullMethodName = "/devicefarm.MediaAdapterControlService/ControlStream"
)

// MediaAdapterControlServiceClient is the client API for MediaAdapterControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediaAdapterControlServiceClient interface {
	ControlStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MediaAdapterMsg, MediaAdapterCommand], error)
}

type mediaAdapterControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaAdapterControlServiceClient(cc grpc.ClientConnInterface) MediaAdapterControlServiceClient {
	return &mediaAdapterControlServiceClient{cc}
}

func (c *mediaAdapterControlServiceClient) ControlStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MediaAdapterMsg, MediaAdapterCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MediaAdapterControlService_ServiceDesc.Streams[0], MediaAdapterControlService_ControlStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MediaAdapterMsg, MediaAdapterCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaAdapterControlService_ControlStreamClient = grpc.BidiStreamingClient[MediaAdapterMsg, MediaAdapterCommand]

// MediaAdapterControlServiceServer is the server API for MediaAdapterControlService service.
// All implementations must embed UnimplementedMediaAdapterControlServiceServer
// for forward compatibility.
type MediaAdapterControlServiceServer interface {
	ControlStream(grpc.BidiStreamingServer[MediaAdapterMsg, MediaAdapterCommand]) error
	mustEmbedUnimplementedMediaAdapterControlServiceServer()
}

// UnimplementedMediaAdapterControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaAdapterControlServiceServer struct{}

func (UnimplementedMediaAdapterControlServiceServer) ControlStream(grpc.BidiStreamingServer[MediaAdapterMsg, MediaAdapterCommand]) error {
	return status.Error(codes.Unimplemented, "method ControlStream not implemented")
}
func (UnimplementedMediaAdapterControlServiceServer) mustEmbedUnimplementedMediaAdapterControlServiceServer() {
}
func (UnimplementedMediaAdapterControlServiceServer) testEmbeddedByValue() {}

// UnsafeMediaAdapterControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaAdapterControlServiceServer will
// result in compilation errors.
type UnsafeMediaAdapterControlServiceServer interface {
	mustEmbedUnimplementedMediaAdapterControlServiceServer()
}

func RegisterMediaAdapterControlServiceServer(s grpc.ServiceRegistrar, srv MediaAdapterControlServiceServer) {
	// If the following call panics, it indicates UnimplementedMediaAdapterControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaAdapterControlService_ServiceDesc, srv)
}

func _MediaAdapterControlService_ControlStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MediaAdapterControlServiceServer).ControlStream(&grpc.GenericServerStream[MediaAdapterMsg, MediaAdapterCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaAdapterControlService_ControlStreamServer = grpc.BidiStreamingServer[MediaAdapterMsg, MediaAdapterCommand]

// MediaAdapterControlService_ServiceDesc is the grpc.ServiceDesc for MediaAdapterControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaAdapterControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devicefarm.MediaAdapterControlService",
	HandlerType: (*MediaAdapterControlServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ControlStream",
			Handler:       _MediaAdapterControlService_ControlStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "relay.proto",
}
