// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.0
// source: relay.proto

package relaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sent by agent-boot → device_farm (replaces the 0x53 binary frame)
type VideoFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serial        string                 `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`                      // device serial (e.g. "192.168.1.10:5555")
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                          // H264 payload (AVCC format)
	IsConfig      bool                   `protobuf:"varint,3,opt,name=is_config,json=isConfig,proto3" json:"is_config,omitempty"` // SPS/PPS config NAL (was flags bit0)
	IsKey         bool                   `protobuf:"varint,4,opt,name=is_key,json=isKey,proto3" json:"is_key,omitempty"`          // IDR keyframe (was flags bit1)
	PtsUs         int64                  `protobuf:"varint,5,opt,name=pts_us,json=ptsUs,proto3" json:"pts_us,omitempty"`          // presentation timestamp µs
	Width         uint32                 `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`                       // screen width (only on is_config frames)
	Height        uint32                 `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`                     // screen height (only on is_config frames)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoFrame) Reset() {
	*x = VideoFrame{}
	mi := &file_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoFrame) ProtoMessage() {}

func (x *VideoFrame) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoFrame.ProtoReflect.Descriptor instead.
func (*VideoFrame) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{0}
}

func (x *VideoFrame) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *VideoFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VideoFrame) GetIsConfig() bool {
	if x != nil {
		return x.IsConfig
	}
	return false
}

func (x *VideoFrame) GetIsKey() bool {
	if x != nil {
		return x.IsKey
	}
	return false
}

func (x *VideoFrame) GetPtsUs() int64 {
	if x != nil {
		return x.PtsUs
	}
	return 0
}

func (x *VideoFrame) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VideoFrame) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Sent by device_farm → agent-boot (scrcpy control bytes OR JSON commands)
type ControlMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serial        string                 `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`                // target device serial
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                    // raw scrcpy control bytes OR JSON command bytes
	IsJson        bool                   `protobuf:"varint,3,opt,name=is_json,json=isJson,proto3" json:"is_json,omitempty"` // true → data is JSON (scrcpy_start, command, ack, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMsg) Reset() {
	*x = ControlMsg{}
	mi := &file_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMsg) ProtoMessage() {}

func (x *ControlMsg) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMsg.ProtoReflect.Descriptor instead.
func (*ControlMsg) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{1}
}

func (x *ControlMsg) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *ControlMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ControlMsg) GetIsJson() bool {
	if x != nil {
		return x.IsJson
	}
	return false
}

// Sent by agent-boot → device_farm: video frame OR JSON control message
// (register / heartbeat / result go as meta)
type AgentMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMsg_Video
	//	*AgentMsg_Meta
	Payload       isAgentMsg_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMsg) Reset() {
	*x = AgentMsg{}
	mi := &file_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMsg) ProtoMessage() {}

func (x *AgentMsg) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMsg.ProtoReflect.Descriptor instead.
func (*AgentMsg) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMsg) GetPayload() isAgentMsg_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMsg) GetVideo() *VideoFrame {
	if x != nil {
		if x, ok := x.Payload.(*AgentMsg_Video); ok {
			return x.Video
		}
	}
	return nil
}

func (x *AgentMsg) GetMeta() []byte {
	if x != nil {
		if x, ok := x.Payload.(*AgentMsg_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

type isAgentMsg_Payload interface {
	isAgentMsg_Payload()
}

type AgentMsg_Video struct {
	Video *VideoFrame `protobuf:"bytes,1,opt,name=video,proto3,oneof"` // H264 frames (high-frequency, ~30fps per phone)
}

type AgentMsg_Meta struct {
	Meta []byte `protobuf:"bytes,2,opt,name=meta,proto3,oneof"` // JSON bytes: register / heartbeat / result (low-frequency)
}

func (*AgentMsg_Video) isAgentMsg_Payload() {}

func (*AgentMsg_Meta) isAgentMsg_Payload() {}

// Agent → Server
type AgentControlMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentControlMsg_Register
	//	*AgentControlMsg_Heartbeat
	//	*AgentControlMsg_Result
	Payload       isAgentControlMsg_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentControlMsg) Reset() {
	*x = AgentControlMsg{}
	mi := &file_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentControlMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentControlMsg) ProtoMessage() {}

func (x *AgentControlMsg) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentControlMsg.ProtoReflect.Descriptor instead.
func (*AgentControlMsg) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{3}
}

func (x *AgentControlMsg) GetPayload() isAgentControlMsg_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentControlMsg) GetRegister() *RegisterMsg {
	if x != nil {
		if x, ok := x.Payload.(*AgentControlMsg_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentControlMsg) GetHeartbeat() *HeartbeatMsg {
	if x != nil {
		if x, ok := x.Payload.(*AgentControlMsg_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentControlMsg) GetResult() *CommandResultMsg {
	if x != nil {
		if x, ok := x.Payload.(*AgentControlMsg_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isAgentControlMsg_Payload interface {
	isAgentControlMsg_Payload()
}

type AgentControlMsg_Register struct {
	Register *RegisterMsg `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentControlMsg_Heartbeat struct {
	Heartbeat *HeartbeatMsg `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentControlMsg_Result struct {
	Result *CommandResultMsg `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

func (*AgentControlMsg_Register) isAgentControlMsg_Payload() {}

func (*AgentControlMsg_Heartbeat) isAgentControlMsg_Payload() {}

func (*AgentControlMsg_Result) isAgentControlMsg_Payload() {}

type RegisterMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelayId       string                 `protobuf:"bytes,1,opt,name=relay_id,json=relayId,proto3" json:"relay_id,omitempty"`
	Serials       []string               `protobuf:"bytes,2,rep,name=serials,proto3" json:"serials,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMsg) Reset() {
	*x = RegisterMsg{}
	mi := &file_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMsg) ProtoMessage() {}

func (x *RegisterMsg) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMsg.ProtoReflect.Descriptor instead.
func (*RegisterMsg) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterMsg) GetRelayId() string {
	if x != nil {
		return x.RelayId
	}
	return ""
}

func (x *RegisterMsg) GetSerials() []string {
	if x != nil {
		return x.Serials
	}
	return nil
}

func (x *RegisterMsg) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterMsg) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterMsg) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type HeartbeatMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelayId       string                 `protobuf:"bytes,1,opt,name=relay_id,json=relayId,proto3" json:"relay_id,omitempty"`
	Serials       []string               `protobuf:"bytes,2,rep,name=serials,proto3" json:"serials,omitempty"`
	Caps          []*DeviceCaps          `protobuf:"bytes,3,rep,name=caps,proto3" json:"caps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMsg) Reset() {
	*x = HeartbeatMsg{}
	mi := &file_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMsg) ProtoMessage() {}

func (x *HeartbeatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMsg.ProtoReflect.Descriptor instead.
func (*HeartbeatMsg) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatMsg) GetRelayId() string {
	if x != nil {
		return x.RelayId
	}
	return ""
}

func (x *HeartbeatMsg) GetSerials() []string {
	if x != nil {
		return x.Serials
	}
	return nil
}

func (x *HeartbeatMsg) GetCaps() []*DeviceCaps {
	if x != nil {
		return x.Caps
	}
	return nil
}

type DeviceCaps struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Serial         string                 `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	AndroidVersion string                 `protobuf:"bytes,2,opt,name=android_version,json=androidVersion,proto3" json:"android_version,omitempty"`
	Sdk            int32                  `protobuf:"varint,3,opt,name=sdk,proto3" json:"sdk,omitempty"`
	Brand          string                 `protobuf:"bytes,4,opt,name=brand,proto3" json:"brand,omitempty"`
	Model          string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	HasU2          bool                   `protobuf:"varint,6,opt,name=has_u2,json=hasU2,proto3" json:"has_u2,omitempty"`
	HasStf         bool                   `protobuf:"varint,7,opt,name=has_stf,json=hasStf,proto3" json:"has_stf,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceCaps) Reset() {
	*x = DeviceCaps{}
	mi := &file_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCaps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCaps) ProtoMessage() {}

func (x *DeviceCaps) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCaps.ProtoReflect.Descriptor instead.
func (*DeviceCaps) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceCaps) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *DeviceCaps) GetAndroidVersion() string {
	if x != nil {
		return x.AndroidVersion
	}
	return ""
}

func (x *DeviceCaps) GetSdk() int32 {
	if x != nil {
		return x.Sdk
	}
	return 0
}

func (x *DeviceCaps) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *DeviceCaps) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeviceCaps) GetHasU2() bool {
	if x != nil {
		return x.HasU2
	}
	return false
}

func (x *DeviceCaps) GetHasStf() bool {
	if x != nil {
		return x.HasStf
	}
	return false
}

type CommandResultMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResultMsg) Reset() {
	*x = CommandResultMsg{}
	mi := &file_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResultMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResultMsg) ProtoMessage() {}

func (x *CommandResultMsg) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResultMsg.ProtoReflect.Descriptor instead.
func (*CommandResultMsg) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{7}
}

func (x *CommandResultMsg) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *CommandResultMsg) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CommandResultMsg) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResultMsg) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CommandResultMsg) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Server → Agent
type ServerControlMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerControlMsg_Ack
	//	*ServerControlMsg_Bootstrap
	//	*ServerControlMsg_RestartU2
	//	*ServerControlMsg_RestartAtx
	//	*ServerControlMsg_Shell
	//	*ServerControlMsg_RestartScrcpy
	Payload       isServerControlMsg_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerControlMsg) Reset() {
	*x = ServerControlMsg{}
	mi := &file_relay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerControlMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerControlMsg) ProtoMessage() {}

func (x *ServerControlMsg) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerControlMsg.ProtoReflect.Descriptor instead.
func (*ServerControlMsg) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{8}
}

func (x *ServerControlMsg) GetPayload() isServerControlMsg_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerControlMsg) GetAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerControlMsg_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ServerControlMsg) GetBootstrap() *BootstrapCmd {
	if x != nil {
		if x, ok := x.Payload.(*ServerControlMsg_Bootstrap); ok {
			return x.Bootstrap
		}
	}
	return nil
}

func (x *ServerControlMsg) GetRestartU2() *RestartU2Cmd {
	if x != nil {
		if x, ok := x.Payload.(*ServerControlMsg_RestartU2); ok {
			return x.RestartU2
		}
	}
	return nil
}

func (x *ServerControlMsg) GetRestartAtx() *RestartAtxCmd {
	if x != nil {
		if x, ok := x.Payload.(*ServerControlMsg_RestartAtx); ok {
			return x.RestartAtx
		}
	}
	return nil
}

func (x *ServerControlMsg) GetShell() *ShellCmd {
	if x != nil {
		if x, ok := x.Payload.(*ServerControlMsg_Shell); ok {
			return x.Shell
		}
	}
	return nil
}

func (x *ServerControlMsg) GetRestartScrcpy() *RestartScrcpyCmd {
	if x != nil {
		if x, ok := x.Payload.(*ServerControlMsg_RestartScrcpy); ok {
			return x.RestartScrcpy
		}
	}
	return nil
}

type isServerControlMsg_Payload interface {
	isServerControlMsg_Payload()
}

type ServerControlMsg_Ack struct {
	Ack *RegisterAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type ServerControlMsg_Bootstrap struct {
	Bootstrap *BootstrapCmd `protobuf:"bytes,2,opt,name=bootstrap,proto3,oneof"`
}

type ServerControlMsg_RestartU2 struct {
	RestartU2 *RestartU2Cmd `protobuf:"bytes,3,opt,name=restart_u2,json=restartU2,proto3,oneof"`
}

type ServerControlMsg_RestartAtx struct {
	RestartAtx *RestartAtxCmd `protobuf:"bytes,4,opt,name=restart_atx,json=restartAtx,proto3,oneof"`
}

type ServerControlMsg_Shell struct {
	Shell *ShellCmd `protobuf:"bytes,5,opt,name=shell,proto3,oneof"`
}

type ServerControlMsg_RestartScrcpy struct {
	RestartScrcpy *RestartScrcpyCmd `protobuf:"bytes,6,opt,name=restart_scrcpy,json=restartScrcpy,proto3,oneof"`
}

func (*ServerControlMsg_Ack) isServerControlMsg_Payload() {}

func (*ServerControlMsg_Bootstrap) isServerControlMsg_Payload() {}

func (*ServerControlMsg_RestartU2) isServerControlMsg_Payload() {}

func (*ServerControlMsg_RestartAtx) isServerControlMsg_Payload() {}

func (*ServerControlMsg_Shell) isServerControlMsg_Payload() {}

func (*ServerControlMsg_RestartScrcpy) isServerControlMsg_Payload() {}

type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_relay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BootstrapCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Serial        string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Timeout       int32                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapCmd) Reset() {
	*x = BootstrapCmd{}
	mi := &file_relay_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapCmd) ProtoMessage() {}

func (x *BootstrapCmd) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapCmd.ProtoReflect.Descriptor instead.
func (*BootstrapCmd) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{10}
}

func (x *BootstrapCmd) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *BootstrapCmd) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *BootstrapCmd) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type RestartU2Cmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Serial        string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Timeout       int32                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartU2Cmd) Reset() {
	*x = RestartU2Cmd{}
	mi := &file_relay_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartU2Cmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartU2Cmd) ProtoMessage() {}

func (x *RestartU2Cmd) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartU2Cmd.ProtoReflect.Descriptor instead.
func (*RestartU2Cmd) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{11}
}

func (x *RestartU2Cmd) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *RestartU2Cmd) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *RestartU2Cmd) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type RestartAtxCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Serial        string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Timeout       int32                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartAtxCmd) Reset() {
	*x = RestartAtxCmd{}
	mi := &file_relay_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartAtxCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartAtxCmd) ProtoMessage() {}

func (x *RestartAtxCmd) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartAtxCmd.ProtoReflect.Descriptor instead.
func (*RestartAtxCmd) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{12}
}

func (x *RestartAtxCmd) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *RestartAtxCmd) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *RestartAtxCmd) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type ShellCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Serial        string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Cmd           string                 `protobuf:"bytes,3,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Timeout       int32                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellCmd) Reset() {
	*x = ShellCmd{}
	mi := &file_relay_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellCmd) ProtoMessage() {}

func (x *ShellCmd) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellCmd.ProtoReflect.Descriptor instead.
func (*ShellCmd) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{13}
}

func (x *ShellCmd) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *ShellCmd) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *ShellCmd) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *ShellCmd) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type RestartScrcpyCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Serial        string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Timeout       int32                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartScrcpyCmd) Reset() {
	*x = RestartScrcpyCmd{}
	mi := &file_relay_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartScrcpyCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartScrcpyCmd) ProtoMessage() {}

func (x *RestartScrcpyCmd) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartScrcpyCmd.ProtoReflect.Descriptor instead.
func (*RestartScrcpyCmd) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{14}
}

func (x *RestartScrcpyCmd) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *RestartScrcpyCmd) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *RestartScrcpyCmd) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type MediaAdapterMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MediaAdapterMsg_Register
	//	*MediaAdapterMsg_Heartbeat
	//	*MediaAdapterMsg_SessionResult
	Payload       isMediaAdapterMsg_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaAdapterMsg) Reset() {
	*x = MediaAdapterMsg{}
	mi := &file_relay_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAdapterMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAdapterMsg) ProtoMessage() {}

func (x *MediaAdapterMsg) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAdapterMsg.ProtoReflect.Descriptor instead.
func (*MediaAdapterMsg) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{15}
}

func (x *MediaAdapterMsg) GetPayload() isMediaAdapterMsg_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MediaAdapterMsg) GetRegister() *MediaAdapterRegister {
	if x != nil {
		if x, ok := x.Payload.(*MediaAdapterMsg_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *MediaAdapterMsg) GetHeartbeat() *MediaAdapterHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*MediaAdapterMsg_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *MediaAdapterMsg) GetSessionResult() *MediaAdapterSessionResult {
	if x != nil {
		if x, ok := x.Payload.(*MediaAdapterMsg_SessionResult); ok {
			return x.SessionResult
		}
	}
	return nil
}

type isMediaAdapterMsg_Payload interface {
	isMediaAdapterMsg_Payload()
}

type MediaAdapterMsg_Register struct {
	Register *MediaAdapterRegister `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type MediaAdapterMsg_Heartbeat struct {
	Heartbeat *MediaAdapterHeartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type MediaAdapterMsg_SessionResult struct {
	SessionResult *MediaAdapterSessionResult `protobuf:"bytes,3,opt,name=session_result,json=sessionResult,proto3,oneof"`
}

func (*MediaAdapterMsg_Register) isMediaAdapterMsg_Payload() {}

func (*MediaAdapterMsg_Heartbeat) isMediaAdapterMsg_Payload() {}

func (*MediaAdapterMsg_SessionResult) isMediaAdapterMsg_Payload() {}

type MediaAdapterRegister struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AdapterId            string                 `protobuf:"bytes,1,opt,name=adapter_id,json=adapterId,proto3" json:"adapter_id,omitempty"`
	RelayId              string                 `protobuf:"bytes,2,opt,name=relay_id,json=relayId,proto3" json:"relay_id,omitempty"`
	Serials              []string               `protobuf:"bytes,3,rep,name=serials,proto3" json:"serials,omitempty"`
	Hostname             string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip                   string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	AdapterVersion       string                 `protobuf:"bytes,6,opt,name=adapter_version,json=adapterVersion,proto3" json:"adapter_version,omitempty"`
	Go2RtcBaseUrl        string                 `protobuf:"bytes,7,opt,name=go2rtc_base_url,json=go2rtcBaseUrl,proto3" json:"go2rtc_base_url,omitempty"`
	StreamSourceTemplate string                 `protobuf:"bytes,8,opt,name=stream_source_template,json=streamSourceTemplate,proto3" json:"stream_source_template,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MediaAdapterRegister) Reset() {
	*x = MediaAdapterRegister{}
	mi := &file_relay_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAdapterRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAdapterRegister) ProtoMessage() {}

func (x *MediaAdapterRegister) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAdapterRegister.ProtoReflect.Descriptor instead.
func (*MediaAdapterRegister) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{16}
}

func (x *MediaAdapterRegister) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

func (x *MediaAdapterRegister) GetRelayId() string {
	if x != nil {
		return x.RelayId
	}
	return ""
}

func (x *MediaAdapterRegister) GetSerials() []string {
	if x != nil {
		return x.Serials
	}
	return nil
}

func (x *MediaAdapterRegister) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MediaAdapterRegister) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *MediaAdapterRegister) GetAdapterVersion() string {
	if x != nil {
		return x.AdapterVersion
	}
	return ""
}

func (x *MediaAdapterRegister) GetGo2RtcBaseUrl() string {
	if x != nil {
		return x.Go2RtcBaseUrl
	}
	return ""
}

func (x *MediaAdapterRegister) GetStreamSourceTemplate() string {
	if x != nil {
		return x.StreamSourceTemplate
	}
	return ""
}

type MediaAdapterHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdapterId     string                 `protobuf:"bytes,1,opt,name=adapter_id,json=adapterId,proto3" json:"adapter_id,omitempty"`
	Serials       []string               `protobuf:"bytes,2,rep,name=serials,proto3" json:"serials,omitempty"`
	Streams       []*MediaStreamStatus   `protobuf:"bytes,3,rep,name=streams,proto3" json:"streams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaAdapterHeartbeat) Reset() {
	*x = MediaAdapterHeartbeat{}
	mi := &file_relay_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAdapterHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAdapterHeartbeat) ProtoMessage() {}

func (x *MediaAdapterHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAdapterHeartbeat.ProtoReflect.Descriptor instead.
func (*MediaAdapterHeartbeat) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{17}
}

func (x *MediaAdapterHeartbeat) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

func (x *MediaAdapterHeartbeat) GetSerials() []string {
	if x != nil {
		return x.Serials
	}
	return nil
}

func (x *MediaAdapterHeartbeat) GetStreams() []*MediaStreamStatus {
	if x != nil {
		return x.Streams
	}
	return nil
}

type MediaStreamStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Serial          string                 `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	StreamName      string                 `protobuf:"bytes,2,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	StreamSource    string                 `protobuf:"bytes,3,opt,name=stream_source,json=streamSource,proto3" json:"stream_source,omitempty"`
	Active          bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Connected       bool                   `protobuf:"varint,5,opt,name=connected,proto3" json:"connected,omitempty"`
	Width           uint32                 `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	Height          uint32                 `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	Frames          uint64                 `protobuf:"varint,8,opt,name=frames,proto3" json:"frames,omitempty"`
	Bytes           uint64                 `protobuf:"varint,9,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Keyframes       uint64                 `protobuf:"varint,10,opt,name=keyframes,proto3" json:"keyframes,omitempty"`
	PublishErrors   uint64                 `protobuf:"varint,11,opt,name=publish_errors,json=publishErrors,proto3" json:"publish_errors,omitempty"`
	LastFrameUnixMs int64                  `protobuf:"varint,12,opt,name=last_frame_unix_ms,json=lastFrameUnixMs,proto3" json:"last_frame_unix_ms,omitempty"`
	Error           string                 `protobuf:"bytes,13,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MediaStreamStatus) Reset() {
	*x = MediaStreamStatus{}
	mi := &file_relay_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaStreamStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaStreamStatus) ProtoMessage() {}

func (x *MediaStreamStatus) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaStreamStatus.ProtoReflect.Descriptor instead.
func (*MediaStreamStatus) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{18}
}

func (x *MediaStreamStatus) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *MediaStreamStatus) GetStreamName() string {
	if x != nil {
		return x.StreamName
	}
	return ""
}

func (x *MediaStreamStatus) GetStreamSource() string {
	if x != nil {
		return x.StreamSource
	}
	return ""
}

func (x *MediaStreamStatus) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *MediaStreamStatus) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *MediaStreamStatus) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaStreamStatus) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaStreamStatus) GetFrames() uint64 {
	if x != nil {
		return x.Frames
	}
	return 0
}

func (x *MediaStreamStatus) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *MediaStreamStatus) GetKeyframes() uint64 {
	if x != nil {
		return x.Keyframes
	}
	return 0
}

func (x *MediaStreamStatus) GetPublishErrors() uint64 {
	if x != nil {
		return x.PublishErrors
	}
	return 0
}

func (x *MediaStreamStatus) GetLastFrameUnixMs() int64 {
	if x != nil {
		return x.LastFrameUnixMs
	}
	return 0
}

func (x *MediaStreamStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MediaAdapterSessionResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Ok              bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error           string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	RetryAfterMs    int32                  `protobuf:"varint,4,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	SessionId       string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Serial          string                 `protobuf:"bytes,6,opt,name=serial,proto3" json:"serial,omitempty"`
	ViewerId        string                 `protobuf:"bytes,7,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"`
	StreamName      string                 `protobuf:"bytes,8,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	StreamSource    string                 `protobuf:"bytes,9,opt,name=stream_source,json=streamSource,proto3" json:"stream_source,omitempty"`
	ExpiresAtUnixMs int64                  `protobuf:"varint,10,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	SdpType         string                 `protobuf:"bytes,11,opt,name=sdp_type,json=sdpType,proto3" json:"sdp_type,omitempty"`
	Sdp             string                 `protobuf:"bytes,12,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MediaAdapterSessionResult) Reset() {
	*x = MediaAdapterSessionResult{}
	mi := &file_relay_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAdapterSessionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAdapterSessionResult) ProtoMessage() {}

func (x *MediaAdapterSessionResult) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAdapterSessionResult.ProtoReflect.Descriptor instead.
func (*MediaAdapterSessionResult) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{19}
}

func (x *MediaAdapterSessionResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MediaAdapterSessionResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *MediaAdapterSessionResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MediaAdapterSessionResult) GetRetryAfterMs() int32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

func (x *MediaAdapterSessionResult) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MediaAdapterSessionResult) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *MediaAdapterSessionResult) GetViewerId() string {
	if x != nil {
		return x.ViewerId
	}
	return ""
}

func (x *MediaAdapterSessionResult) GetStreamName() string {
	if x != nil {
		return x.StreamName
	}
	return ""
}

func (x *MediaAdapterSessionResult) GetStreamSource() string {
	if x != nil {
		return x.StreamSource
	}
	return ""
}

func (x *MediaAdapterSessionResult) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

func (x *MediaAdapterSessionResult) GetSdpType() string {
	if x != nil {
		return x.SdpType
	}
	return ""
}

func (x *MediaAdapterSessionResult) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

type MediaAdapterCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MediaAdapterCommand_Ack
	//	*MediaAdapterCommand_StartSession
	//	*MediaAdapterCommand_AnswerSession
	//	*MediaAdapterCommand_HeartbeatSession
	//	*MediaAdapterCommand_CloseSession
	Payload       isMediaAdapterCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaAdapterCommand) Reset() {
	*x = MediaAdapterCommand{}
	mi := &file_relay_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAdapterCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAdapterCommand) ProtoMessage() {}

func (x *MediaAdapterCommand) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAdapterCommand.ProtoReflect.Descriptor instead.
func (*MediaAdapterCommand) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{20}
}

func (x *MediaAdapterCommand) GetPayload() isMediaAdapterCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MediaAdapterCommand) GetAck() *MediaAdapterAck {
	if x != nil {
		if x, ok := x.Payload.(*MediaAdapterCommand_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *MediaAdapterCommand) GetStartSession() *MediaAdapterStartSessionCmd {
	if x != nil {
		if x, ok := x.Payload.(*MediaAdapterCommand_StartSession); ok {
			return x.StartSession
		}
	}
	return nil
}

func (x *MediaAdapterCommand) GetAnswerSession() *MediaAdapterAnswerSessionCmd {
	if x != nil {
		if x, ok := x.Payload.(*MediaAdapterCommand_AnswerSession); ok {
			return x.AnswerSession
		}
	}
	return nil
}

func (x *MediaAdapterCommand) GetHeartbeatSession() *MediaAdapterHeartbeatSessionCmd {
	if x != nil {
		if x, ok := x.Payload.(*MediaAdapterCommand_HeartbeatSession); ok {
			return x.HeartbeatSession
		}
	}
	return nil
}

func (x *MediaAdapterCommand) GetCloseSession() *MediaAdapterCloseSessionCmd {
	if x != nil {
		if x, ok := x.Payload.(*MediaAdapterCommand_CloseSession); ok {
			return x.CloseSession
		}
	}
	return nil
}

type isMediaAdapterCommand_Payload interface {
	isMediaAdapterCommand_Payload()
}

type MediaAdapterCommand_Ack struct {
	Ack *MediaAdapterAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type MediaAdapterCommand_StartSession struct {
	StartSession *MediaAdapterStartSessionCmd `protobuf:"bytes,2,opt,name=start_session,json=startSession,proto3,oneof"`
}

type MediaAdapterCommand_AnswerSession struct {
	AnswerSession *MediaAdapterAnswerSessionCmd `protobuf:"bytes,3,opt,name=answer_session,json=answerSession,proto3,oneof"`
}

type MediaAdapterCommand_HeartbeatSession struct {
	HeartbeatSession *MediaAdapterHeartbeatSessionCmd `protobuf:"bytes,4,opt,name=heartbeat_session,json=heartbeatSession,proto3,oneof"`
}

type MediaAdapterCommand_CloseSession struct {
	CloseSession *MediaAdapterCloseSessionCmd `protobuf:"bytes,5,opt,name=close_session,json=closeSession,proto3,oneof"`
}

func (*MediaAdapterCommand_Ack) isMediaAdapterCommand_Payload() {}

func (*MediaAdapterCommand_StartSession) isMediaAdapterCommand_Payload() {}

func (*MediaAdapterCommand_AnswerSession) isMediaAdapterCommand_Payload() {}

func (*MediaAdapterCommand_HeartbeatSession) isMediaAdapterCommand_Payload() {}

func (*MediaAdapterCommand_CloseSession) isMediaAdapterCommand_Payload() {}

type MediaAdapterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaAdapterAck) Reset() {
	*x = MediaAdapterAck{}
	mi := &file_relay_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAdapterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAdapterAck) ProtoMessage() {}

func (x *MediaAdapterAck) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAdapterAck.ProtoReflect.Descriptor instead.
func (*MediaAdapterAck) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{21}
}

func (x *MediaAdapterAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MediaAdapterStartSessionCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Serial        string                 `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial,omitempty"`
	ViewerId      string                 `protobuf:"bytes,5,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,6,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	Control       bool                   `protobuf:"varint,7,opt,name=control,proto3" json:"control,omitempty"`
	Profile       string                 `protobuf:"bytes,8,opt,name=profile,proto3" json:"profile,omitempty"`
	MaxFps        int32                  `protobuf:"varint,9,opt,name=max_fps,json=maxFps,proto3" json:"max_fps,omitempty"`
	MaxWidth      int32                  `protobuf:"varint,10,opt,name=max_width,json=maxWidth,proto3" json:"max_width,omitempty"`
	Bitrate       int32                  `protobuf:"varint,11,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaAdapterStartSessionCmd) Reset() {
	*x = MediaAdapterStartSessionCmd{}
	mi := &file_relay_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAdapterStartSessionCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAdapterStartSessionCmd) ProtoMessage() {}

func (x *MediaAdapterStartSessionCmd) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAdapterStartSessionCmd.ProtoReflect.Descriptor instead.
func (*MediaAdapterStartSessionCmd) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{22}
}

func (x *MediaAdapterStartSessionCmd) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MediaAdapterStartSessionCmd) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *MediaAdapterStartSessionCmd) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MediaAdapterStartSessionCmd) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *MediaAdapterStartSessionCmd) GetViewerId() string {
	if x != nil {
		return x.ViewerId
	}
	return ""
}

func (x *MediaAdapterStartSessionCmd) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *MediaAdapterStartSessionCmd) GetControl() bool {
	if x != nil {
		return x.Control
	}
	return false
}

func (x *MediaAdapterStartSessionCmd) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *MediaAdapterStartSessionCmd) GetMaxFps() int32 {
	if x != nil {
		return x.MaxFps
	}
	return 0
}

func (x *MediaAdapterStartSessionCmd) GetMaxWidth() int32 {
	if x != nil {
		return x.MaxWidth
	}
	return 0
}

func (x *MediaAdapterStartSessionCmd) GetBitrate() int32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

type MediaAdapterAnswerSessionCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SdpType       string                 `protobuf:"bytes,3,opt,name=sdp_type,json=sdpType,proto3" json:"sdp_type,omitempty"`
	Sdp           string                 `protobuf:"bytes,4,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaAdapterAnswerSessionCmd) Reset() {
	*x = MediaAdapterAnswerSessionCmd{}
	mi := &file_relay_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAdapterAnswerSessionCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAdapterAnswerSessionCmd) ProtoMessage() {}

func (x *MediaAdapterAnswerSessionCmd) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAdapterAnswerSessionCmd.ProtoReflect.Descriptor instead.
func (*MediaAdapterAnswerSessionCmd) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{23}
}

func (x *MediaAdapterAnswerSessionCmd) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MediaAdapterAnswerSessionCmd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MediaAdapterAnswerSessionCmd) GetSdpType() string {
	if x != nil {
		return x.SdpType
	}
	return ""
}

func (x *MediaAdapterAnswerSessionCmd) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

type MediaAdapterHeartbeatSessionCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaAdapterHeartbeatSessionCmd) Reset() {
	*x = MediaAdapterHeartbeatSessionCmd{}
	mi := &file_relay_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAdapterHeartbeatSessionCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAdapterHeartbeatSessionCmd) ProtoMessage() {}

func (x *MediaAdapterHeartbeatSessionCmd) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAdapterHeartbeatSessionCmd.ProtoReflect.Descriptor instead.
func (*MediaAdapterHeartbeatSessionCmd) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{24}
}

func (x *MediaAdapterHeartbeatSessionCmd) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MediaAdapterHeartbeatSessionCmd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MediaAdapterHeartbeatSessionCmd) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type MediaAdapterCloseSessionCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaAdapterCloseSessionCmd) Reset() {
	*x = MediaAdapterCloseSessionCmd{}
	mi := &file_relay_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAdapterCloseSessionCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAdapterCloseSessionCmd) ProtoMessage() {}

func (x *MediaAdapterCloseSessionCmd) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAdapterCloseSessionCmd.ProtoReflect.Descriptor instead.
func (*MediaAdapterCloseSessionCmd) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{25}
}

func (x *MediaAdapterCloseSessionCmd) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MediaAdapterCloseSessionCmd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_relay_proto protoreflect.FileDescriptor

const file_relay_proto_rawDesc = "" +
	"\n" +
	"\vrelay.proto\x12\n" +
	"devicefarm\"\xb1\x01\n" +
	"\n" +
	"VideoFrame\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1b\n" +
	"\tis_config\x18\x03 \x01(\bR\bisConfig\x12\x15\n" +
	"\x06is_key\x18\x04 \x01(\bR\x05isKey\x12\x15\n" +
	"\x06pts_us\x18\x05 \x01(\x03R\x05ptsUs\x12\x14\n" +
	"\x05width\x18\x06 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\a \x01(\rR\x06height\"Q\n" +
	"\n" +
	"ControlMsg\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x17\n" +
	"\ais_json\x18\x03 \x01(\bR\x06isJson\"[\n" +
	"\bAgentMsg\x12.\n" +
	"\x05video\x18\x01 \x01(\v2\x16.devicefarm.VideoFrameH\x00R\x05video\x12\x14\n" +
	"\x04meta\x18\x02 \x01(\fH\x00R\x04metaB\t\n" +
	"\apayload\"\xc5\x01\n" +
	"\x0fAgentControlMsg\x125\n" +
	"\bregister\x18\x01 \x01(\v2\x17.devicefarm.RegisterMsgH\x00R\bregister\x128\n" +
	"\theartbeat\x18\x02 \x01(\v2\x18.devicefarm.HeartbeatMsgH\x00R\theartbeat\x126\n" +
	"\x06result\x18\x03 \x01(\v2\x1c.devicefarm.CommandResultMsgH\x00R\x06resultB\t\n" +
	"\apayload\"\x93\x01\n" +
	"\vRegisterMsg\x12\x19\n" +
	"\brelay_id\x18\x01 \x01(\tR\arelayId\x12\x18\n" +
	"\aserials\x18\x02 \x03(\tR\aserials\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\"o\n" +
	"\fHeartbeatMsg\x12\x19\n" +
	"\brelay_id\x18\x01 \x01(\tR\arelayId\x12\x18\n" +
	"\aserials\x18\x02 \x03(\tR\aserials\x12*\n" +
	"\x04caps\x18\x03 \x03(\v2\x16.devicefarm.DeviceCapsR\x04caps\"\xbb\x01\n" +
	"\n" +
	"DeviceCaps\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\x12'\n" +
	"\x0fandroid_version\x18\x02 \x01(\tR\x0eandroidVersion\x12\x10\n" +
	"\x03sdk\x18\x03 \x01(\x05R\x03sdk\x12\x14\n" +
	"\x05brand\x18\x04 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x15\n" +
	"\x06has_u2\x18\x06 \x01(\bR\x05hasU2\x12\x17\n" +
	"\ahas_stf\x18\a \x01(\bR\x06hasStf\"\x84\x01\n" +
	"\x10CommandResultMsg\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xf2\x02\n" +
	"\x10ServerControlMsg\x12+\n" +
	"\x03ack\x18\x01 \x01(\v2\x17.devicefarm.RegisterAckH\x00R\x03ack\x128\n" +
	"\tbootstrap\x18\x02 \x01(\v2\x18.devicefarm.BootstrapCmdH\x00R\tbootstrap\x129\n" +
	"\n" +
	"restart_u2\x18\x03 \x01(\v2\x18.devicefarm.RestartU2CmdH\x00R\trestartU2\x12<\n" +
	"\vrestart_atx\x18\x04 \x01(\v2\x19.devicefarm.RestartAtxCmdH\x00R\n" +
	"restartAtx\x12,\n" +
	"\x05shell\x18\x05 \x01(\v2\x14.devicefarm.ShellCmdH\x00R\x05shell\x12E\n" +
	"\x0erestart_scrcpy\x18\x06 \x01(\v2\x1c.devicefarm.RestartScrcpyCmdH\x00R\rrestartScrcpyB\t\n" +
	"\apayload\"'\n" +
	"\vRegisterAck\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"W\n" +
	"\fBootstrapCmd\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x05R\atimeout\"W\n" +
	"\fRestartU2Cmd\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x05R\atimeout\"X\n" +
	"\rRestartAtxCmd\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x05R\atimeout\"e\n" +
	"\bShellCmd\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x10\n" +
	"\x03cmd\x18\x03 \x01(\tR\x03cmd\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x05R\atimeout\"[\n" +
	"\x10RestartScrcpyCmd\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x05R\atimeout\"\xef\x01\n" +
	"\x0fMediaAdapterMsg\x12>\n" +
	"\bregister\x18\x01 \x01(\v2 .devicefarm.MediaAdapterRegisterH\x00R\bregister\x12A\n" +
	"\theartbeat\x18\x02 \x01(\v2!.devicefarm.MediaAdapterHeartbeatH\x00R\theartbeat\x12N\n" +
	"\x0esession_result\x18\x03 \x01(\v2%.devicefarm.MediaAdapterSessionResultH\x00R\rsessionResultB\t\n" +
	"\apayload\"\x9d\x02\n" +
	"\x14MediaAdapterRegister\x12\x1d\n" +
	"\n" +
	"adapter_id\x18\x01 \x01(\tR\tadapterId\x12\x19\n" +
	"\brelay_id\x18\x02 \x01(\tR\arelayId\x12\x18\n" +
	"\aserials\x18\x03 \x03(\tR\aserials\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\x12'\n" +
	"\x0fadapter_version\x18\x06 \x01(\tR\x0eadapterVersion\x12&\n" +
	"\x0fgo2rtc_base_url\x18\a \x01(\tR\rgo2rtcBaseUrl\x124\n" +
	"\x16stream_source_template\x18\b \x01(\tR\x14streamSourceTemplate\"\x89\x01\n" +
	"\x15MediaAdapterHeartbeat\x12\x1d\n" +
	"\n" +
	"adapter_id\x18\x01 \x01(\tR\tadapterId\x12\x18\n" +
	"\aserials\x18\x02 \x03(\tR\aserials\x127\n" +
	"\astreams\x18\x03 \x03(\v2\x1d.devicefarm.MediaStreamStatusR\astreams\"\x8b\x03\n" +
	"\x11MediaStreamStatus\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\x12\x1f\n" +
	"\vstream_name\x18\x02 \x01(\tR\n" +
	"streamName\x12#\n" +
	"\rstream_source\x18\x03 \x01(\tR\fstreamSource\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x12\x1c\n" +
	"\tconnected\x18\x05 \x01(\bR\tconnected\x12\x14\n" +
	"\x05width\x18\x06 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\a \x01(\rR\x06height\x12\x16\n" +
	"\x06frames\x18\b \x01(\x04R\x06frames\x12\x14\n" +
	"\x05bytes\x18\t \x01(\x04R\x05bytes\x12\x1c\n" +
	"\tkeyframes\x18\n" +
	" \x01(\x04R\tkeyframes\x12%\n" +
	"\x0epublish_errors\x18\v \x01(\x04R\rpublishErrors\x12+\n" +
	"\x12last_frame_unix_ms\x18\f \x01(\x03R\x0flastFrameUnixMs\x12\x14\n" +
	"\x05error\x18\r \x01(\tR\x05error\"\xfa\x02\n" +
	"\x19MediaAdapterSessionResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12$\n" +
	"\x0eretry_after_ms\x18\x04 \x01(\x05R\fretryAfterMs\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06serial\x18\x06 \x01(\tR\x06serial\x12\x1b\n" +
	"\tviewer_id\x18\a \x01(\tR\bviewerId\x12\x1f\n" +
	"\vstream_name\x18\b \x01(\tR\n" +
	"streamName\x12#\n" +
	"\rstream_source\x18\t \x01(\tR\fstreamSource\x12+\n" +
	"\x12expires_at_unix_ms\x18\n" +
	" \x01(\x03R\x0fexpiresAtUnixMs\x12\x19\n" +
	"\bsdp_type\x18\v \x01(\tR\asdpType\x12\x10\n" +
	"\x03sdp\x18\f \x01(\tR\x03sdp\"\xa0\x03\n" +
	"\x13MediaAdapterCommand\x12/\n" +
	"\x03ack\x18\x01 \x01(\v2\x1b.devicefarm.MediaAdapterAckH\x00R\x03ack\x12N\n" +
	"\rstart_session\x18\x02 \x01(\v2'.devicefarm.MediaAdapterStartSessionCmdH\x00R\fstartSession\x12Q\n" +
	"\x0eanswer_session\x18\x03 \x01(\v2(.devicefarm.MediaAdapterAnswerSessionCmdH\x00R\ranswerSession\x12Z\n" +
	"\x11heartbeat_session\x18\x04 \x01(\v2+.devicefarm.MediaAdapterHeartbeatSessionCmdH\x00R\x10heartbeatSession\x12N\n" +
	"\rclose_session\x18\x05 \x01(\v2'.devicefarm.MediaAdapterCloseSessionCmdH\x00R\fcloseSessionB\t\n" +
	"\apayload\"+\n" +
	"\x0fMediaAdapterAck\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xc6\x02\n" +
	"\x1bMediaAdapterStartSessionCmd\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06serial\x18\x04 \x01(\tR\x06serial\x12\x1b\n" +
	"\tviewer_id\x18\x05 \x01(\tR\bviewerId\x12\x1f\n" +
	"\vttl_seconds\x18\x06 \x01(\x05R\n" +
	"ttlSeconds\x12\x18\n" +
	"\acontrol\x18\a \x01(\bR\acontrol\x12\x18\n" +
	"\aprofile\x18\b \x01(\tR\aprofile\x12\x17\n" +
	"\amax_fps\x18\t \x01(\x05R\x06maxFps\x12\x1b\n" +
	"\tmax_width\x18\n" +
	" \x01(\x05R\bmaxWidth\x12\x18\n" +
	"\abitrate\x18\v \x01(\x05R\abitrate\"\x89\x01\n" +
	"\x1cMediaAdapterAnswerSessionCmd\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x19\n" +
	"\bsdp_type\x18\x03 \x01(\tR\asdpType\x12\x10\n" +
	"\x03sdp\x18\x04 \x01(\tR\x03sdp\"\x80\x01\n" +
	"\x1fMediaAdapterHeartbeatSessionCmd\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x05R\n" +
	"ttlSeconds\"[\n" +
	"\x1bMediaAdapterCloseSessionCmd\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId2J\n" +
	"\fRelayService\x12:\n" +
	"\x06Stream\x12\x14.devicefarm.AgentMsg\x1a\x16.devicefarm.ControlMsg(\x010\x012e\n" +
	"\x13AgentControlService\x12N\n" +
	"\rControlStream\x12\x1b.devicefarm.AgentControlMsg\x1a\x1c.devicefarm.ServerControlMsg(\x010\x012o\n" +
	"\x1aMediaAdapterControlService\x12Q\n" +
	"\rControlStream\x12\x1b.devicefarm.MediaAdapterMsg\x1a\x1f.devicefarm.MediaAdapterCommand(\x010\x01B3Z1devicefarm/media-adapter/internal/grpcapi/relaypbb\x06proto3"

var (
	file_relay_proto_rawDescOnce sync.Once
	file_relay_proto_rawDescData []byte
)

func file_relay_proto_rawDescGZIP() []byte {
	file_relay_proto_rawDescOnce.Do(func() {
		file_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_proto_rawDesc), len(file_relay_proto_rawDesc)))
	})
	return file_relay_proto_rawDescData
}

var file_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_relay_proto_goTypes = []any{
	(*VideoFrame)(nil),                      // 0: devicefarm.VideoFrame
	(*ControlMsg)(nil),                      // 1: devicefarm.ControlMsg
	(*AgentMsg)(nil),                        // 2: devicefarm.AgentMsg
	(*AgentControlMsg)(nil),                 // 3: devicefarm.AgentControlMsg
	(*RegisterMsg)(nil),                     // 4: devicefarm.RegisterMsg
	(*HeartbeatMsg)(nil),                    // 5: devicefarm.HeartbeatMsg
	(*DeviceCaps)(nil),                      // 6: devicefarm.DeviceCaps
	(*CommandResultMsg)(nil),                // 7: devicefarm.CommandResultMsg
	(*ServerControlMsg)(nil),                // 8: devicefarm.ServerControlMsg
	(*RegisterAck)(nil),                     // 9: devicefarm.RegisterAck
	(*BootstrapCmd)(nil),                    // 10: devicefarm.BootstrapCmd
	(*RestartU2Cmd)(nil),                    // 11: devicefarm.RestartU2Cmd
	(*RestartAtxCmd)(nil),                   // 12: devicefarm.RestartAtxCmd
	(*ShellCmd)(nil),                        // 13: devicefarm.ShellCmd
	(*RestartScrcpyCmd)(nil),                // 14: devicefarm.RestartScrcpyCmd
	(*MediaAdapterMsg)(nil),                 // 15: devicefarm.MediaAdapterMsg
	(*MediaAdapterRegister)(nil),            // 16: devicefarm.MediaAdapterRegister
	(*MediaAdapterHeartbeat)(nil),           // 17: devicefarm.MediaAdapterHeartbeat
	(*MediaStreamStatus)(nil),               // 18: devicefarm.MediaStreamStatus
	(*MediaAdapterSessionResult)(nil),       // 19: devicefarm.MediaAdapterSessionResult
	(*MediaAdapterCommand)(nil),             // 20: devicefarm.MediaAdapterCommand
	(*MediaAdapterAck)(nil),                 // 21: devicefarm.MediaAdapterAck
	(*MediaAdapterStartSessionCmd)(nil),     // 22: devicefarm.MediaAdapterStartSessionCmd
	(*MediaAdapterAnswerSessionCmd)(nil),    // 23: devicefarm.MediaAdapterAnswerSessionCmd
	(*MediaAdapterHeartbeatSessionCmd)(nil), // 24: devicefarm.MediaAdapterHeartbeatSessionCmd
	(*MediaAdapterCloseSessionCmd)(nil),     // 25: devicefarm.MediaAdapterCloseSessionCmd
}
var file_relay_proto_depIdxs = []int32{
	0,  // 0: devicefarm.AgentMsg.video:type_name -> devicefarm.VideoFrame
	4,  // 1: devicefarm.AgentControlMsg.register:type_name -> devicefarm.RegisterMsg
	5,  // 2: devicefarm.AgentControlMsg.heartbeat:type_name -> devicefarm.HeartbeatMsg
	7,  // 3: devicefarm.AgentControlMsg.result:type_name -> devicefarm.CommandResultMsg
	6,  // 4: devicefarm.HeartbeatMsg.caps:type_name -> devicefarm.DeviceCaps
	9,  // 5: devicefarm.ServerControlMsg.ack:type_name -> devicefarm.RegisterAck
	10, // 6: devicefarm.ServerControlMsg.bootstrap:type_name -> devicefarm.BootstrapCmd
	11, // 7: devicefarm.ServerControlMsg.restart_u2:type_name -> devicefarm.RestartU2Cmd
	12, // 8: devicefarm.ServerControlMsg.restart_atx:type_name -> devicefarm.RestartAtxCmd
	13, // 9: devicefarm.ServerControlMsg.shell:type_name -> devicefarm.ShellCmd
	14, // 10: devicefarm.ServerControlMsg.restart_scrcpy:type_name -> devicefarm.RestartScrcpyCmd
	16, // 11: devicefarm.MediaAdapterMsg.register:type_name -> devicefarm.MediaAdapterRegister
	17, // 12: devicefarm.MediaAdapterMsg.heartbeat:type_name -> devicefarm.MediaAdapterHeartbeat
	19, // 13: devicefarm.MediaAdapterMsg.session_result:type_name -> devicefarm.MediaAdapterSessionResult
	18, // 14: devicefarm.MediaAdapterHeartbeat.streams:type_name -> devicefarm.MediaStreamStatus
	21, // 15: devicefarm.MediaAdapterCommand.ack:type_name -> devicefarm.MediaAdapterAck
	22, // 16: devicefarm.MediaAdapterCommand.start_session:type_name -> devicefarm.MediaAdapterStartSessionCmd
	23, // 17: devicefarm.MediaAdapterCommand.answer_session:type_name -> devicefarm.MediaAdapterAnswerSessionCmd
	24, // 18: devicefarm.MediaAdapterCommand.heartbeat_session:type_name -> devicefarm.MediaAdapterHeartbeatSessionCmd
	25, // 19: devicefarm.MediaAdapterCommand.close_session:type_name -> devicefarm.MediaAdapterCloseSessionCmd
	2,  // 20: devicefarm.RelayService.Stream:input_type -> devicefarm.AgentMsg
	3,  // 21: devicefarm.AgentControlService.ControlStream:input_type -> devicefarm.AgentControlMsg
	15, // 22: devicefarm.MediaAdapterControlService.ControlStream:input_type -> devicefarm.MediaAdapterMsg
	1,  // 23: devicefarm.RelayService.Stream:output_type -> devicefarm.ControlMsg
	8,  // 24: devicefarm.AgentControlService.ControlStream:output_type -> devicefarm.ServerControlMsg
	20, // 25: devicefarm.MediaAdapterControlService.ControlStream:output_type -> devicefarm.MediaAdapterCommand
	23, // [23:26] is the sub-list for method output_type
	20, // [20:23] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_relay_proto_init() }
func file_relay_proto_init() {
	if File_relay_proto != nil {
		return
	}
	file_relay_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentMsg_Video)(nil),
		(*AgentMsg_Meta)(nil),
	}
	file_relay_proto_msgTypes[3].OneofWrappers = []any{
		(*AgentControlMsg_Register)(nil),
		(*AgentControlMsg_Heartbeat)(nil),
		(*AgentControlMsg_Result)(nil),
	}
	file_relay_proto_msgTypes[8].OneofWrappers = []any{
		(*ServerControlMsg_Ack)(nil),
		(*ServerControlMsg_Bootstrap)(nil),
		(*ServerControlMsg_RestartU2)(nil),
		(*ServerControlMsg_RestartAtx)(nil),
		(*ServerControlMsg_Shell)(nil),
		(*ServerControlMsg_RestartScrcpy)(nil),
	}
	file_relay_proto_msgTypes[15].OneofWrappers = []any{
		(*MediaAdapterMsg_Register)(nil),
		(*MediaAdapterMsg_Heartbeat)(nil),
		(*MediaAdapterMsg_SessionResult)(nil),
	}
	file_relay_proto_msgTypes[20].OneofWrappers = []any{
		(*MediaAdapterCommand_Ack)(nil),
		(*MediaAdapterCommand_StartSession)(nil),
		(*MediaAdapterCommand_AnswerSession)(nil),
		(*MediaAdapterCommand_HeartbeatSession)(nil),
		(*MediaAdapterCommand_CloseSession)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_proto_rawDesc), len(file_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_relay_proto_goTypes,
		DependencyIndexes: file_relay_proto_depIdxs,
		MessageInfos:      file_relay_proto_msgTypes,
	}.Build()
	File_relay_proto = out.File
	file_relay_proto_goTypes = nil
	file_relay_proto_depIdxs = nil
}
