"""Scenario DSL validation error codes (DF-T-04-002)."""

from __future__ import annotations

DUPLICATE_STEP_ID = "DUPLICATE_STEP_ID"
UNKNOWN_STEP_TYPE = "UNKNOWN_STEP_TYPE"
NESTED_DEPTH_EXCEEDED = "NESTED_DEPTH_EXCEEDED"
INVALID_GRAPH_EDGE = "INVALID_GRAPH_EDGE"
INVALID_STEP_SHAPE = "INVALID_STEP_SHAPE"
KIND_BODY_MISMATCH = "KIND_BODY_MISMATCH"
